# Generated by Django 3.0.1 on 2020-01-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovRotativo',
            new_name='Rotativo',
        ),
    ]
