# Generated by Django 3.0.1 on 2020-01-05 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0002_auto_20200103_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='veiculo',
            name='observacoes',
        ),
    ]
