# Generated by Django 3.0.1 on 2020-01-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0004_auto_20200104_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotativo',
            name='checkout',
            field=models.DateField(auto_now=True),
        ),
    ]
