# Generated by Django 3.0.1 on 2020-01-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamento', '0005_auto_20200104_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotativo',
            name='checkin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='rotativo',
            name='checkout',
            field=models.DateField(),
        ),
    ]
